# Generated by Django 5.0.6 on 2024-06-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0002_goods_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_page.goods')),
            ],
        ),
    ]
